# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-15 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_bid_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempicture',
            name='mediumThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail (medium)'),
        ),
        migrations.AddField(
            model_name='itempicture',
            name='smallThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail (small)'),
        ),
    ]
