# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20170715_2127'),
        ('auctions', '0042_auto_20170715_1602'),
    ]

    operations = [
    ]
