# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 04:21
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_merge_20170716_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempicture',
            name='mediumThumbnail',
        ),
        migrations.RemoveField(
            model_name='itempicture',
            name='smallThumbnail',
        ),
        migrations.AddField(
            model_name='itempicture',
            name='medium_thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail (medium)'),
        ),
        migrations.AddField(
            model_name='itempicture',
            name='small_thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail (small)'),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='picture',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
